name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  install-and-tests:
    name: 1.Install dependencies and run all tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:nowatch

  build:
    needs: install-and-tests
    name: 2.Build project
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build

  deploy:
    needs: build
    name: 3.Deploy to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
